id = 1
host = "127.0.0.1"
port = 8901
data_path = "/var/lib/cnosdb/meta"

[log]
level = "info"
path = "/var/log/cnosdb"

[meta_init]
cluster_name = "cluster_xxx"
admin_user = "root"
system_tenant = "cnosdb"
default_database = ["public", "usage_schema"]

[heartbeat]
heartbeat_recheck_interval = 300
heartbeat_expired_interval = 600
