[query]
max_server_connections = 10240
query_sql_limit = 16777216   # 16 * 1024 * 1024
write_sql_limit = 167772160   # 160 * 1024 * 1024
auth_enabled = false

[storage]
# Directory for summary: $path/summary/
# Directory for index: $path/index/$database/
# Directory for tsm: $path/data/$database/tsm/
# Directory for delta: $path/data/$database/delta/
path = '/tmp/cnosdb/1001/db'
max_summary_size = "128M" # 134217728
base_file_size = "16M" # 16777216
max_level = 4
compact_trigger_file_num = 4
compact_trigger_cold_duration = "1h"
max_compact_size = "2G" # 2147483648
max_concurrent_compaction = 4
strict_write = false

[wal]
enabled = true
path = '/tmp/cnosdb/1001/wal'
max_file_size = "1G" # 1073741824
sync = false
sync_interval = "0" # h, m, s

[cache]
max_buffer_size = "128M" # 134217728
max_immutable_number = 4

[log]
level = 'info'
path = '/tmp/cnosdb/1001/log'

[security]
# [security.tls_config]
# certificate = "./config/tls/server.crt"
# private_key = "./config/tls/server.key"

[cluster]
node_id = 1001
name = 'cluster_xxx'
meta_service_addr = '127.0.0.1:21001'

http_listen_addr = '127.0.0.1:31001'
grpc_listen_addr = '127.0.0.1:31002'
tcp_listen_addr = '127.0.0.1:31003'
flight_rpc_listen_addr = '127.0.0.1:31004'

[hintedoff]
enable = true
path = '/tmp/cnosdb/1001/hh'

